name: 'Action availability'
description: 'Provide a description here'
author: 'Nicolas Filippelli'
inputs:
  GITHUB_TOKEN:
    description: 'User token of service account.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
